--
-- PostgreSQL database dump
--

\restrict IYmPLh9anqygq79zPAcfZhFQJdMmbH7cgGpUKHRGZp1aZ6IkWrlvecEHpowNxqU

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-10-07 17:14:29

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5067 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 16423)
-- Name: actividad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad (
    idactividad integer NOT NULL,
    idproyecto integer,
    idresponsable integer,
    nombre character varying(100),
    fechainicio date,
    fechatermino date,
    porcentaje numeric(5,2),
    estadoactividad integer
);


ALTER TABLE public.actividad OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16395)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    idcliente integer,
    nombre character varying(60)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16420)
-- Name: estado_proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado_proyecto (
    idproyecto integer,
    descripcion character varying(40)
);


ALTER TABLE public.estado_proyecto OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16433)
-- Name: estado_riesgo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado_riesgo (
    idestadoriesgo integer NOT NULL,
    descripcion character varying(50)
);


ALTER TABLE public.estado_riesgo OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16437)
-- Name: estado_riesgo_idestadoriesgo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estado_riesgo ALTER COLUMN idestadoriesgo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estado_riesgo_idestadoriesgo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16439)
-- Name: impacto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.impacto (
    id integer NOT NULL,
    descripcion character varying(50)
);


ALTER TABLE public.impacto OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16438)
-- Name: impacto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.impacto ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.impacto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16392)
-- Name: perfil_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.perfil_usuario (
    idperfil character varying(30),
    descripcion character varying(60)
);


ALTER TABLE public.perfil_usuario OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16398)
-- Name: prioridad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prioridad (
    idprioridad character varying(30),
    descripcion character varying(60)
);


ALTER TABLE public.prioridad OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16402)
-- Name: proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proyecto (
    id_proyecto integer NOT NULL,
    nombre character varying(200) NOT NULL,
    id_cliente integer NOT NULL,
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone,
    id_estatus integer NOT NULL,
    porcentaje numeric(5,2) DEFAULT 0.00,
    prioridad integer NOT NULL
);


ALTER TABLE public.proyecto OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16401)
-- Name: proyecto_id_proyecto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.proyecto_id_proyecto_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.proyecto_id_proyecto_seq OWNER TO postgres;

--
-- TOC entry 5068 (class 0 OID 0)
-- Dependencies: 223
-- Name: proyecto_id_proyecto_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.proyecto_id_proyecto_seq OWNED BY public.proyecto.id_proyecto;


--
-- TOC entry 233 (class 1259 OID 16444)
-- Name: riesgo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.riesgo (
    idriesgo integer NOT NULL,
    descripcion character varying(255),
    idproyecto integer NOT NULL,
    impacto integer NOT NULL,
    probabilidad numeric(5,2),
    estado integer NOT NULL
);


ALTER TABLE public.riesgo OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16443)
-- Name: riesgo_idriesgo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.riesgo ALTER COLUMN idriesgo ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.riesgo_idriesgo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_empleado integer NOT NULL,
    nombre character varying(50),
    apepat character varying(50),
    apemat character varying(50),
    contrasena character varying(100),
    correo character varying(100),
    id_perfil character varying(30)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16419)
-- Name: usuario_id_empleado_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_empleado ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.usuario_id_empleado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4896 (class 2604 OID 16405)
-- Name: proyecto id_proyecto; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto ALTER COLUMN id_proyecto SET DEFAULT nextval('public.proyecto_id_proyecto_seq'::regclass);


--
-- TOC entry 5055 (class 0 OID 16423)
-- Dependencies: 227
-- Data for Name: actividad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividad (idactividad, idproyecto, idresponsable, nombre, fechainicio, fechatermino, porcentaje, estadoactividad) FROM stdin;
\.


--
-- TOC entry 5049 (class 0 OID 16395)
-- Dependencies: 221
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (idcliente, nombre) FROM stdin;
1	TELCEL
2	DIAGEO
3	SERVIFE
4	BIS
\.


--
-- TOC entry 5054 (class 0 OID 16420)
-- Dependencies: 226
-- Data for Name: estado_proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estado_proyecto (idproyecto, descripcion) FROM stdin;
1	En progreso
2	En riesgo
3	Retrasado
\.


--
-- TOC entry 5056 (class 0 OID 16433)
-- Dependencies: 228
-- Data for Name: estado_riesgo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estado_riesgo (idestadoriesgo, descripcion) FROM stdin;
2	MITIGADO
1	FINALIZADO
4	ABIERTO
\.


--
-- TOC entry 5059 (class 0 OID 16439)
-- Dependencies: 231
-- Data for Name: impacto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.impacto (id, descripcion) FROM stdin;
1	BAJO
2	MEDIO
4	ALTO
\.


--
-- TOC entry 5048 (class 0 OID 16392)
-- Dependencies: 220
-- Data for Name: perfil_usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.perfil_usuario (idperfil, descripcion) FROM stdin;
A	ADMINISTRADOR
LP	LIDER PROYECTO
D	DIRECTOR
PM	PROJECT MANAGER
C	CONSULTOR
\.


--
-- TOC entry 5050 (class 0 OID 16398)
-- Dependencies: 222
-- Data for Name: prioridad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prioridad (idprioridad, descripcion) FROM stdin;
3	ALTA
2	MEDIA
1	BAJA
\.


--
-- TOC entry 5052 (class 0 OID 16402)
-- Dependencies: 224
-- Data for Name: proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proyecto (id_proyecto, nombre, id_cliente, fecha_inicio, fecha_fin, id_estatus, porcentaje, prioridad) FROM stdin;
1	Administración BD de colaboradores de Bis Soluciones	1	2026-09-01 00:00:00	2026-09-30 00:00:00	1	0.00	1
\.


--
-- TOC entry 5061 (class 0 OID 16444)
-- Dependencies: 233
-- Data for Name: riesgo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.riesgo (idriesgo, descripcion, idproyecto, impacto, probabilidad, estado) FROM stdin;
1	CREDENCIALES DE ACCESO INCORRECTAS AL EQUIPO DE COMPUTO	1	4	70.00	2
\.


--
-- TOC entry 5047 (class 0 OID 16389)
-- Dependencies: 219
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_empleado, nombre, apepat, apemat, contrasena, correo, id_perfil) FROM stdin;
5	LUISA	MARTINEZ	AVILES	$2b$10$oAg4FfpVr.ekI0neW1.7h.1WCqdSDah.zLw6ClRQnePLbUNrezQ9W	luisa.martinez@bism.com.mx	LP
4	GERARDO MANUEL	GOMEZ	VAZQUEZ	$2b$10$Qvbv.JnWAw7nW9Jn7cLVku3B/nF33wsi2SH2aDhl1EKKiAcFUDfmm	gerardo.gomez@bism.com.mx	C
6	JUAN	GARCIA	LOPEZ	$2b$10$md3X.Zuh3ntn/bpatE2P6OKI85oVZMvsdMw24JEiGb7h/p5Ix60f.	juan.garcia@bism.com.mx	A
\.


--
-- TOC entry 5069 (class 0 OID 0)
-- Dependencies: 229
-- Name: estado_riesgo_idestadoriesgo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estado_riesgo_idestadoriesgo_seq', 4, true);


--
-- TOC entry 5070 (class 0 OID 0)
-- Dependencies: 230
-- Name: impacto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.impacto_id_seq', 4, true);


--
-- TOC entry 5071 (class 0 OID 0)
-- Dependencies: 223
-- Name: proyecto_id_proyecto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proyecto_id_proyecto_seq', 1, true);


--
-- TOC entry 5072 (class 0 OID 0)
-- Dependencies: 232
-- Name: riesgo_idriesgo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.riesgo_idriesgo_seq', 1, true);


--
-- TOC entry 5073 (class 0 OID 0)
-- Dependencies: 225
-- Name: usuario_id_empleado_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_empleado_seq', 6, true);


--
-- TOC entry 4899 (class 2606 OID 16415)
-- Name: proyecto proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_pkey PRIMARY KEY (id_proyecto);


-- Completed on 2026-10-07 17:14:29

--
-- PostgreSQL database dump complete
--

\unrestrict IYmPLh9anqygq79zPAcfZhFQJdMmbH7cgGpUKHRGZp1aZ6IkWrlvecEHpowNxqU

